%% Define initial boundary condition

function fxBnd=bct_iniFxBnd(mp,nBnd)

%% Define fixed boundary on the left end
if nBnd==1
    fxBnd=[-(2*mp.bctLn+3),-(2*mp.bctLn+3),...
        -(2*mp.bctLn+3),mp.ly+(2*mp.bctLn+3),...
        1,0;];
else
    fxBnd=[-(2*mp.bctLn+3),-(2*mp.bctLn+3),...
        -(2*mp.bctLn+3),mp.ly+(2*mp.bctLn+3),...
        1,0;...
        mp.lx+(2*mp.bctLn+3),-(2*mp.bctLn+3),...
        mp.lx+(2*mp.bctLn+3),mp.ly+(2*mp.bctLn+3),...
        -1,0;];
end

end